# Site settings
author: Joshua Collins Roque
title: Coding a lifetime
header-img: img/home-bg.png
email: codejoshuaroque@gmail.com
copyright_name: Joshua Collins Roque
description: > # this means to ignore newlines until "baseurl:"
  A long short story
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  codenameransom

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
